name: CI Build

on:
  push:
    branches: [ f-workflow ]
  pull_request:
    branches: [ f-workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 7   # Java 7 isn’t available anymore

      - name: Build with Maven
        run: mvn -B clean install -DskipTests
